<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
		<ContentTargetFolders>.</ContentTargetFolders>
		<PackageId>UmbracoSeoVisualizer</PackageId>
		<PackageTags>umbraco umbraco-marketplace plugin package</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

    <GenerateDocumentationFile>True</GenerateDocumentationFile>

    <!-- PDBs beside DLLs -->
    <DebugType>portable</DebugType>

    <!-- Publish symbols as a separate .snupkg -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- Make SourceLink work + deterministic CI build -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/enkelmedia/Umbraco-SeoVisualizer</RepositoryUrl>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="[17.0.0-rc4,18)" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[17.0.0-rc4,18)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SeoVisualizer.Core\SeoVisualizer.Core.csproj" />
	</ItemGroup>
  <ItemGroup>
    <Compile Remove="wwwroot\App_Plugins\SeoVizualizer\**" />
    <Content Remove="wwwroot\App_Plugins\SeoVizualizer\**" />
    <EmbeddedResource Remove="wwwroot\App_Plugins\SeoVizualizer\**" />
    <None Remove="wwwroot\App_Plugins\SeoVizualizer\**" />
  </ItemGroup>
	<ItemGroup>
		<None Include="build\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
  <Target Name="PreBuildClientRelease" BeforeTargets="PreBuild" Condition="$(ConfigurationName) == Release">
    <Message Text="Building client side assets using npm." Importance="High" />
    <Exec Command="npm install" WorkingDirectory="$(ProjectDir)\Client" />
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)\Client" />
    <!-- Ensure nothing from /Client is included in the build artifact -->
    <ItemGroup>
      <Compile Remove="Client\**" />
      <Content Remove="Client\**" />
      <EmbeddedResource Remove="Client\**" />
      <None Remove="Client\**" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="wwwroot\App_Plugins\SeoVizualizer\**" />
      <Content Include="wwwroot\App_Plugins\SeoVizualizer\dist\**" />
    </ItemGroup>
  </Target>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="$(ConfigurationName) != DebugNoClientSideBuild">
    <Message Text="Client side code was built." Importance="High" />
  </Target>
</Project>
